# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

career:
  pidl: "https://sites.google.com/snu.ac.kr/a2i2/"
  gsds: "https://gsds.snu.ac.kr/"
  snu: "https://www.topuniversities.com/universities/seoul-national-university"
  hust: "https://en.wikipedia.org/wiki/Hanoi_University_of_Science_and_Technology"
  srv: "https://www.samsung.com/vn/about-us/business-area/r-and-d-center/"


error_image: 'Unable to Load Image'
collections:
  backgrounds:
    output: true
  papers:
    output: true
  projects:
    output: true

skills:
  coding_language:
    title: Programming
    details: Python, C/C++, JavaScript, TypeScript
    rate: 80
  dl_framework:
    title: Machine Learning
    details: Amazon Sagemaker, Tensorflow, Pytorch, Tensorrt, DeepStream, SkLearn
    rate: 90
  database:
    title: Database Management
    details: Redis, MongoDb, MySQL, Postgres, Neo4J
    rate: 70
  dev:
    title: DevOps
    details: Android, Django, Angular, Jekyll, Docker
    rate: 55

title: DTLam26
name: DUONG TUNG LAM
email: dtlam26@snu.ac.kr
author:
  name: Nativv Studios
  about: Jekyll Theme

short_description: >- # this means to ignore newlines until "baseurl:"
  In 2019, I had completed my BSc degree on Electrical & Telecommunication (Advanced Program) 
  from <a href='"career.hust"'>Hanoi University of Science and Technology (HUST), Vietnam</a> 
  and started my Graduted Student journey in 2020 at <a href='"${career.snu}"'>Seoul National University (SNU), Korea</a>. 
  After 3 years of extensive studying and programming development, I earned my Master of Science in Electrical & Computer Engineering and published two academic papers. 
  Thanks to the guidance of Prof. Sang Kyun Cha, the former Dean of <a href='"${career.gsds}"'>Seoul National University Graduate School of Data Science</a> 
  and <a href='"${career.pidl}"'>PIDLab</a>, I had been given opportunities to work, design and implement different types of IoT AI infrastructures, while improving my knowledge on various Machine Learning algorithms. 
  Since then, I have been a Senior Computer Vision Engineer in Samsung Vietnam R&D Center with my main scope of developing visual solutions for Samsung Multimedia Apps which play keyfeatures in Samsung S series. 
  I dream of becoming a successful man in AI Production field that galvanize myself to embrace challenges, learn from failures and setbacks, and persist in coping with obstacles.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


contacts:
  - title: twitter
    url: 'https://twitter.com/dtlam26'
  - title: github
    url:  'https://github.com/dtlam26'
  - title: stack-overflow
    url:  'https://stackoverflow.com/users/13726782/dtlam26'
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  # - title: instagram
  #   url: 'https://example.com/@jekyllrb'
  - title: linkedin
    url: 'https://www.linkedin.com/in/lamduongtung'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: email
    url: mailto:dtlamw26@snu.ac.kr

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
